server:
  tomcat:
    connection-timeout: 20000

spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  data:
    redis:
      host: ${spring.redis.host:127.0.0.1}
      port: ${spring.redis.port:6379}
#      password:
      database: 0
      timeout: 5s

  redis:
    redisson:
      codec: org.redisson.codec.JsonJacksonCodec
      threads: ${redisson.threads:8}
      netty-threads: ${redisson.nettyThreads:16}

      lockWatchdogTimeout: 30000
      keepPubSubOrder: true


      singleServerConfig:
        address: redis://${spring.redis.host:127.0.0.1}:${spring.redis.port:6379}
        password: ${spring.redis.password}
        database: ${spring.redis.database:0}

        connectTimeout: 10000 # ms

        # 链接池
        connectionMinimumIdleSize: 8 # 最小空闲连接，避免频繁创建连接
        connectionPoolSize: 32 # 连接池大小，默认64

        subscriptionsPerConnection: 5 # 单链接最大订阅数
        # 发布和订阅连接的最小空闲连接数。默认值: 1
        subscriptionConnectionMinimumIdleSize: 1
        # 发布和订阅连接池大小。默认值: 50
        subscriptionConnectionPoolSize: 50
        # DNS监测时间间隔，单位：毫秒。默认值: 5000
        dnsMonitoringInterval: 5000
        # 连接空闲超时，单位：毫秒。默认值: 10000
        idleConnectionTimeout: 10000

        # 超时控制
        timeout: ${spring.redis.timeout:3000} # ms
        retry-attempts: 3 # 重试次数，失败快速降级
        retry-interval: 1500 # 重试间隔 ms